apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-xdty
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkwch-fix-0075-0036-tenant/tkwch-fix-0075-0036-app/devfile-sample-xdty@sha256:bfa731a6ddc84587654b59783caee4a17f604c48056f61b9a60d60597467d313
        name: my-nodejs
        resources: {}
status: {}
